export const PRODUCT_CATEGORIES = Object.freeze({
  SPARE_PARTS: 'SPARE_PARTS',
  LUBRICANTS: 'LUBRICANTS',
  ACCESSORIES: 'ACCESSORIES',
  CONSUMABLES: 'CONSUMABLES',
  OTHER: 'OTHER',
});

export const ROLES = Object.freeze({
  ADMIN: 'ADMIN',
});

export const JOB_TYPES = Object.freeze({
  FULL_SERVICE: 'FULL_SERVICE',
  ENGINE_JOB: 'ENGINE_JOB',
});

export const JOB_STATUSES = Object.freeze({
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
});

export const PAYMENT_STATUSES = Object.freeze({
  UNPAID: 'UNPAID',
  PARTIALLY_PAID: 'PARTIALLY_PAID',
  PAID: 'PAID',
});

export const PAYMENT_METHODS = Object.freeze({
  CASH: 'CASH',
  UPI: 'UPI',
  CARD: 'CARD',
  BANK_TRANSFER: 'BANK_TRANSFER',
  OTHER: 'OTHER',
});

export const INVENTORY_MOVEMENT_TYPES = Object.freeze({
  PURCHASE_RECEIVED: 'PURCHASE_RECEIVED',
  SERVICE_USAGE: 'SERVICE_USAGE',
  RETURN: 'RETURN',
  MANUAL_ADJUSTMENT: 'MANUAL_ADJUSTMENT',
  CORRECTION: 'CORRECTION',
});

export const SUPPLIER_ORDER_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  ORDERED: 'ORDERED',
  RECEIVED: 'RECEIVED',
  CANCELLED: 'CANCELLED',
});

export const MONEY_SOURCES = Object.freeze({
  GARAGE_MONEY: 'GARAGE_MONEY',
  NAIM_PERSONAL: 'NAIM_PERSONAL',
  IMRAN_PERSONAL: 'IMRAN_PERSONAL',
});

export const EXPENSE_CATEGORIES = Object.freeze({
  ELECTRICITY: 'ELECTRICITY',
  RENT: 'RENT',
  GARAGE_MAINTENANCE: 'GARAGE_MAINTENANCE',
  TOOLS: 'TOOLS',
  SUPPLIER_PAYMENT: 'SUPPLIER_PAYMENT',
  OTHER: 'OTHER',
});

export const PARTNERS = Object.freeze({
  NAIM: 'NAIM',
  IMRAN: 'IMRAN',
});

export const PARTNER_TRANSACTION_TYPES = Object.freeze({
  PERSONAL_WITHDRAWAL: 'PERSONAL_WITHDRAWAL',
  OUT_OF_POCKET_EXPENSE: 'OUT_OF_POCKET_EXPENSE',
  CAPITAL_INJECTION: 'CAPITAL_INJECTION',
});

export const STOCK_STATUSES = Object.freeze({
  IN_STOCK: 'IN_STOCK',
  LOW_STOCK: 'LOW_STOCK',
  OUT_OF_STOCK: 'OUT_OF_STOCK',
});

export const VEHICLE_TYPES = Object.freeze({
  MOTORCYCLE: 'MOTORCYCLE',
  SCOOTER: 'SCOOTER',
  MOPED: 'MOPED',
  OTHER: 'OTHER',
});

export const INSPECTION_CATEGORIES = [
  'ENGINE_OIL',
  'BRAKES',
  'TIRES',
  'ELECTRICAL',
  'BATTERY',
  'CHAIN_SPROCKET',
  'SUSPENSION',
  'LIGHTS',
  'BODY_PANELS',
  'GENERAL',
];

export const INSPECTION_CONDITIONS = Object.freeze({
  GOOD: 'GOOD',
  FAIR: 'FAIR',
  POOR: 'POOR',
  CRITICAL: 'CRITICAL',
  REPLACED: 'REPLACED',
});

export const PRIORITIES = Object.freeze({
  LOW: 'LOW',
  NORMAL: 'NORMAL',
  HIGH: 'HIGH',
  URGENT: 'URGENT',
});

export const SETTLEMENT_STATUSES = Object.freeze({
  DRAFT: 'DRAFT',
  FINALIZED: 'FINALIZED',
});

export const JOB_PRIORITIES = PRIORITIES;
